<!-- FOOTER -->
        <div id="footer">
            <map name="dmshandbook" id="dmshandbook">
                <area alt="Doctors' Management Service, Inc. 2012 Handbook"
                shape="rect" coords="1, 1, 135, 60" href="contact.php">
            </map>
            <div class="one-fourth">
                <p class="bold">
                    <span aria-hidden="true" data-icon="&#59254;"></span><br />
                    <a href="http://www.salusresourcegroup.com/">
                        The Salus Resource Group
                    </a>
                </p>
                <p>
                    <q>Providing Comprehensive Solutions To The Dental And
                    Medical Community To Enhance Personal and Professional
                    Growth.</q>
                </p>
            </div>
            <div class="one-fourth">
                <p class="bold"><span aria-hidden="true" data-icon="&#127916;"></span><br /><a href="https://www.youtube.com/user/DoctorsManagementSvc">YouTube<br />Channel</a></p>
                <p>Subscribe to our YouTube<br />Channel to stay up to date.</p>
            </div>
            <div class="one-fourth">
                <p class="bold">
                    <span aria-hidden="true" data-icon="&#128214;"></span><br />
                    <a href="contact.php">
                        RECEIVE OUR 2015 HANDBOOK
                    </a>
                </p>
                <p>
                    Please contact us to receive your copy.
                </p>
            </div>
            <div class="one-fourth">
                <p class="bold">
                    <span data-icon="&#128362;"></span><br /><a href="contact.php">New EHR<br />Implementation</a></p>
                    <p>Please contact us to discuss details and set up a free demonstration!</p>
            </div>
            <div id="footerNav">
                <nav>
                    <ul>
                        <li>
                            <a href="index.php">Home</a>
                        </li>
                        <!--<li>
                            <a href="careers.php">Careers</a>
                        </li>-->
                        <li>
                            <a href="contact.php">Contact Us</a>
                        </li>
                        <li>
                            <a href="https://docs.google.com/forms/d/188uq-xE4kSRhVoEzV_LruxKI6PgdVeIRhf8_SWJlGXM/viewform?usp=send_form">Careers</a>
                        </li>
                        <li>
                            <a href="privacypolicy.php">Privacy
                            Policy</a>
                        </li>
                        <li>
                            <a href="sitemap.php">Site Map</a>
                        </li>
                    </ul>
                </nav>
                <div style="width:56%;height:auto;float:right;">
                    <p id="addressCredits">CONTACT <a href=
                    "mailto:tim@doctorsmanagementservice.org">tim@doctorsmanagementservice.org</a><br>
                    <strong>DMS |</strong> 944 Washington St., Suite 1 South
                    Easton, MA 02375 <strong><br>P</strong> 508.238.8646
                    <strong>F</strong> 508.230.9772<br>
                    © 2014 Doctors' Management Service, Inc. All Rights Reserved.<br>
                    Site designed by <a href=
                    "http://www.ncdesigns-studio.com/index.html">NC Designs</a>.</p>
                </div>
            </div>
        <!-- END FOOTER -->
    </body>
</html>