<!doctype html>
<!--[if lt IE 7 ]> <html class="no-js ie ie6" lang="en"> <![endif]-->
<!--[if IE 7 ]>    <html class="no-js ie ie7" lang="en"> <![endif]-->
<!--[if IE 8 ]>    <html class="no-js ie ie8" lang="en"> <![endif]-->
<!--[if IE 9 ]>    <html class="no-js ie ie9" lang="en"> <![endif]-->
<!--[if (gt IE 9)|!(IE)]><!--> <html class="no-js" lang="en"> <!--<![endif]-->
<head>
<meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1" />
<title><?php echo $page_title; ?></title>

<meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
<meta name="description" content="DMS now stands as a premier management company with a robust reference list of clients who attest to the model of enhancing services and keeping in strong communication to maximize reimbursement and quality for practices." />
<meta name="keywords" content="Doctors' Management Service Inc., Medical billing, Third Party, Consultations, Medicare Audit" />
<meta http-equiv="expires" content="January 1 2013" />
<meta name="author" content="Nelson Correia" />
<meta name="contact" content="tim@doctorsmanagementservice.org" />
<meta name="robots" content="index" />
<meta name="copyright" content="January 2012" />
<meta name="google-site-verification" content="L1xftfeDPftcEUCqhiXX8etjE-2SrsZ41F-8Dt4SDZ0" />

<link rel="icon" href="DMS_Logo_Symbol_Only.ico" type="image/x-icon" />
 
 <!--[if lt IE 9]>
<script src="http://html5shiv.googlecode.com/svn/trunk/html5.js"></script>
<![endif]-->

<link rel="stylesheet" type="text/css" href="dms.css" />

<!-- Counter/Statistics -->
<script language="JavaScript"
src="http://us.js2.yimg.com/us.js.yimg.com/lib/smb/js/hosting/cp/js_source/whv2_001.js">
</script>
<script language="javascript">geovisit();</script>
<noscript><img src="http://visit.webhosting.yahoo.com/visit.gif?time"
alt="setstats" border="0" width="1" height="1"></noscript>

<script src="js/bw-menu.js" type="text/javascript"></script>

<div id="fb-root"></div>
<script type="text/javascript">
  (function(d, s, id) {
      var js, fjs = d.getElementsByTagName(s)[0];
        if (d.getElementById(id)) return;
          js = d.createElement(s); js.id = id;
          js.src = "//connect.facebook.net/en_US/all.js#xfbml=1";
          fjs.parentNode.insertBefore(js, fjs);
        }(document, 'script', 'facebook-jssdk'));
</script>


<script type='text/javascript' src="http://code.jquery.com/jquery-1.5.2.js"></script>
<script src="SpryAssets/SpryAccordion.js" type="text/javascript"></script>
<link href="SpryAssets/SpryAccordion.css" rel="stylesheet" type="text/css" />
</head>

<body>

<script type="text/javascript">

  var _gaq = _gaq || [];
  _gaq.push(['_setAccount', 'UA-33866682-1']);
  _gaq.push(['_trackPageview']);

  (function() {
    var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
    ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
    var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
  })();

</script>

  <div id="wrapContainer">
      <map name="bannerImg" id="bannerImg">
      <area alt="Doctors' Management Service, Inc." shape="rect" coords="150, 0, 350, 150" href="index.php" />
      </map>
        <div id="banner">
          <div id="bannerCallOut">
              <p>Prompt, Professional Service | <span id="bannerCallOutPhone">Call 508.238.8646</span>
        </p>
                <div id="bannerCallOutSocial">
          <script src="//platform.linkedin.com/in.js" type="text/javascript"></script>
<script type="IN/FollowCompany" data-id="2453756" data-counter="right"></script>
              </div>
                <div class="fb-like" data-href="http://www.doctorsmanagementservice.org/index.php" data-send="false" data-layout="button_count" data-width="60" data-show-faces="false" data-font="verdana">
        </div>
        <div id="twitterShare"><a href="https://twitter.com/DoctorsMgmtSvc" class="twitter-follow-button" data-show-count="false">Follow @DoctorsMgmtSvc</a>
<script>!function(d,s,id){var js,fjs=d.getElementsByTagName(s)[0];if(!d.getElementById(id)){js=d.createElement(s);js.id=id;js.src="//platform.twitter.com/widgets.js";fjs.parentNode.insertBefore(js,fjs);}}(document,"script","twitter-wjs");</script></div>
      </div>
            <div id="companyTitle">
        <h1>Doctors' Management Service, Inc.</h1>
            </div>
            <img src="images/bg1.png" width="1200" height="157" alt="Doctors' Management Service, Inc."  usemap="#bannerImg" />