<div id="sideNav">
<p>SERVICES</p>
	<nav>
		<ul>
			
			<li><a href="fullCredentialing.php">Provider Credentialing</a></li>
			<li><a href="fullMedicalBilling.php">Full Medical Billing</a></li>
			<li><a href="complianceAuditing.php">Compliance Auditing</a></li>
			<li><a href="docTraining.php">Documentation Training</a></li>
			<li><a href="businessConsultation.php">Business Consultation</a></li>
			<li><a href="accountManagement.php">Account Management</a></li>
			<li><a href="codingCharts.php">Coding Charts</a></li>
			<li>Medical Courier Service</li>
		</ul>
	</nav>
</div>