<div id="sideBar">
<iframe id="ytplayer" type="text/html" width="200" height="112" src="https://www.youtube.com/embed/?listType=user_uploads&list=DoctorsManagementSvc" frameborder="0" allowfullscreen></iframe>
        <!--[if lte IE 9]><div class="hide"><![endif]-->
            <a class="twitter-timeline" href="https://twitter.com/DoctorsMgmtSvc" data-widget-id="319432892256231425" data-border-color="#07acef" data-highlight="DMS Tweets">Tweets by @DoctorsMgmtSvc</a>
<script>!function(d,s,id){var js,fjs=d.getElementsByTagName(s)[0];if(!d.getElementById(id)){js=d.createElement(s);js.id=id;js.src="//platform.twitter.com/widgets.js";fjs.parentNode.insertBefore(js,fjs);}}(document,"script","twitter-wjs");</script><!--[if lte IE 9]></div><![endif]-->
</div><!-- END SIDEBAR -->
