<div id="sideBar">
    <!-- <div id="player"></div> -->
        <!--[if lte IE 6]><div class="hide"><![endif]-->
            <a class="twitter-timeline" href="https://twitter.com/DoctorsMgmtSvc" data-widget-id="319432892256231425" data-border-color="#07acef" data-highlight="DMS Tweets">Tweets by @DoctorsMgmtSvc</a>
<script>!function(d,s,id){var js,fjs=d.getElementsByTagName(s)[0];if(!d.getElementById(id)){js=d.createElement(s);js.id=id;js.src="//platform.twitter.com/widgets.js";fjs.parentNode.insertBefore(js,fjs);}}(document,"script","twitter-wjs");</script><!--[if lte IE 6]></div><![endif]-->
</div><!-- END SIDEBAR -->
