<!-- SIDEBAR --><div id="sideBar">
        			<div class="sideBarTitle">Call Us Today! You may opt for Doctors' Management Service to:</div>
            		<ul>
            			<li>Code your records
                        </li>
                		<li>Hold consultations with your office personnel
                        </li>
                		<li>Conduct Credentialing
                        </li>
                		<li>Perform Documentation Training
                        </li>
                		<li>Or handle all aspects of billing for your account
                        </li>
            		</ul>
					<div>
					<div class="sideBarTitle">
						
					</div>
					<div id="sideBarYouTube">
						<!--[if lte IE 6]>
						<div class="hide">
						<![endif]-->
					<script>
new TWTR.Widget({
  version: 2,
  type: 'profile',
  rpp: 4,
  interval: 30000,
  width: 222,
  height: 222,
  theme: {
    shell: {
      background: '#006e99',
      color: '#ffffff'
    },
    tweets: {
      background: '#000000',
      color: '#ffffff',
      links: '#af8e09'
    }
  },
  features: {
    scrollbar: true,
    loop: false,
    live: false,
    behavior: 'all'
  }
}).render().setUser('DoctorsMgmtSvc&exclude_replies=true').start();/* Updated this filter to remove replies 042712 */
</script>

<!--[if lte IE 6]></div><![endif]--></div>
        		</div>
        		
				<div class="hide"><div class="fb-like-box" data-href="https://www.facebook.com/pages/Doctors-Management-Service-Inc/169401349832449?ref=tn_tnmn" data-width="220" data-height="200" data-show-faces="true" data-stream="true" data-border-color="#6a6678" data-header="false"></div></div>
        		</div>
				<!-- END SIDEBAR -->