<!-- TOP NAV -->
        	<div id="topNav">
				<nav>
					<ul>
						<li id="youAreHere">
                        	<a href="#">Home
                            </a>
                        </li>
						<li>
                        	<a href="ourServices.php" onMouseOver="setMenu('menuSubTwo')" onMouseOut="clearMenu('menuSubTwo')">Our Services
                            </a>
                      	</li>
						<li>
                        	<a href="company.php">Our Company
                            </a>
                      	</li>
						<li ><a href="testimonials.php">Testimonials</a></li>
						<!-- <li><a href="pressRelease.php">Press Release</a></li> -->
						<li>
                        	<a href="contact.php">Contact Us
                            </a>
                       	</li>
					</ul>
                    <ul id="menuSubTwo" class="menuVert" onMouseOver="setMenu('menuSubTwo')" onMouseOut="clearMenu('menuSubTwo')">
						
			<li><a href="fullCredentialing.php">Provider Credentialing</a></li>
			<li><a href="fullMedicalBilling.php">Full Medical Billing</a></li>
			<li><a href="complianceAuditing.php">Compliance Auditing</a></li>
			<li><a href="docTraining.php">Documentation Training</a></li>
			<li><a href="businessConsultation.php">Business Consultation</a></li>
			<li><a href="accountManagement.php">Account Management</a></li>
			<li><a href="codingCharts.php">Coding Charts</a></li>
			<li><a href="medicalCourier.php">Medical Courier Service</a></li>
					</ul>
				</nav>
			</div>